[package]
name = "only_one"
version = "0.1.0"
authors = ["Nossie531"]
edition = "2024"
description = "Value consumption helper."
repository = "https://github.com/nossie531/only_one"
license = "MIT OR Apache-2.0"
keywords = ["drop"]
categories = ["no-std"]
